# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  config_file:
    type: string
    default: ""
    description: >
      Blackbox Exporter configuration file (yaml).
      Refer to https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md for
      full details.
      The modules provided via blackbox_exporter_probes interface are merged with the modules defined here.
  probes_file:
    type: string
    default: ""
    description: >
      Scrape config for Prometheus in a file (yaml).
      Refer to https://github.com/prometheus/blackbox_exporter#prometheus-configuration for full
      details.
      The probes provided via blackbox_exporter_probes interface are merged with the probes defined here.
      The relation probes are hashed to ensure uniquess in the blackbox_probes.py library.
      However, in case of same `job_name` the relation probe takes precedence,
      overriding the corresponding file probe.
  cpu:
    description: |
      K8s cpu resource limit, e.g. "1" or "500m". Default is unset (no limit). This value is used
      for the "limits" portion of the resource requirements (the "requests" portion is
      automatically deduced from it).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
  memory:
    description: |
      K8s memory resource limit, e.g. "1Gi". Default is unset (no limit). This value is used
      for the "limits" portion of the resource requirements (the "requests" portion is
      automatically deduced from it).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
